import { describe, expect, it } from 'vitest';
import type { OverallCoverage } from '../aggregator';
import { generateMarkdownReport } from '../report';

describe('generateMarkdownReport', () => {
  it('should generate report with all passing modules', () => {
    const coverage: OverallCoverage = {
      percentage: 85.5,
      covered: 855,
      total: 1000,
      modules: [
        {
          module: ':core:common',
          coverage: { covered: 855, missed: 145, total: 1000, percentage: 85.5 },
          threshold: 80,
          passed: true,
        },
      ],
    };

    const report = generateMarkdownReport(coverage, 'Code Coverage Report');

    expect(report).toContain('## 📊 Code Coverage Report');
    expect(report).toContain('**Overall Coverage: 85.5%**');
    expect(report).toContain(':core:common');
    expect(report).toContain('85.5%');
    expect(report).toContain('80%');
    expect(report).toContain('✅');
    expect(report).toContain('<!-- kover-coverage-report -->');
  });

  it('should show ⚠️ for modules with null coverage', () => {
    const coverage: OverallCoverage = {
      percentage: 85.5,
      covered: 855,
      total: 1000,
      modules: [
        {
          module: ':core',
          coverage: null,
          threshold: 0,
          passed: false,
        },
        {
          module: ':core:common',
          coverage: { covered: 855, missed: 145, total: 1000, percentage: 85.5 },
          threshold: 80,
          passed: true,
        },
      ],
    };

    const report = generateMarkdownReport(coverage, 'Coverage Report');

    expect(report).toContain(':core');
    expect(report).toContain('N/A');
    expect(report).toContain('⚠️');
    expect(report).toContain(':core:common');
    expect(report).toContain('✅');
  });

  it('should show ❌ for failing modules', () => {
    const coverage: OverallCoverage = {
      percentage: 63.3,
      covered: 950,
      total: 1500,
      modules: [
        {
          module: ':feature:auth',
          coverage: { covered: 150, missed: 350, total: 500, percentage: 30.0 },
          threshold: 70,
          passed: false,
        },
      ],
    };

    const report = generateMarkdownReport(coverage, 'Coverage Report');

    expect(report).toContain(':feature:auth');
    expect(report).toContain('30.0%');
    expect(report).toContain('70%');
    expect(report).toContain('❌');
  });

  it('should sort modules alphabetically', () => {
    const coverage: OverallCoverage = {
      percentage: 75.0,
      covered: 750,
      total: 1000,
      modules: [
        {
          module: ':feature:auth',
          coverage: { covered: 300, missed: 200, total: 500, percentage: 60.0 },
          threshold: 70,
          passed: false,
        },
        {
          module: ':core:common',
          coverage: { covered: 250, missed: 50, total: 300, percentage: 83.3 },
          threshold: 80,
          passed: true,
        },
        {
          module: ':data:repository',
          coverage: { covered: 200, missed: 0, total: 200, percentage: 100.0 },
          threshold: 75,
          passed: true,
        },
      ],
    };

    const report = generateMarkdownReport(coverage, 'Coverage Report');

    // Check that modules appear in alphabetical order
    const coreIndex = report.indexOf(':core:common');
    const dataIndex = report.indexOf(':data:repository');
    const featureIndex = report.indexOf(':feature:auth');

    expect(coreIndex).toBeLessThan(dataIndex);
    expect(dataIndex).toBeLessThan(featureIndex);
  });

  it('should include legend and footer', () => {
    const coverage: OverallCoverage = {
      percentage: 85.5,
      covered: 855,
      total: 1000,
      modules: [
        {
          module: ':app',
          coverage: { covered: 855, missed: 145, total: 1000, percentage: 85.5 },
          threshold: 80,
          passed: true,
        },
      ],
    };

    const report = generateMarkdownReport(coverage, 'Coverage Report');

    expect(report).toContain('### Legend');
    expect(report).toContain('✅ Coverage meets threshold');
    expect(report).toContain('❌ Coverage below threshold');
    expect(report).toContain('⚠️ No coverage report found');
    expect(report).toContain('_Generated by [kover-report-action]');
  });

  it('should handle mixed status modules', () => {
    const coverage: OverallCoverage = {
      percentage: 73.3,
      covered: 1100,
      total: 1500,
      modules: [
        {
          module: ':core:common',
          coverage: { covered: 800, missed: 200, total: 1000, percentage: 80.0 },
          threshold: 80,
          passed: true,
        },
        {
          module: ':core:testing',
          coverage: null,
          threshold: 0,
          passed: false,
        },
        {
          module: ':data:repository',
          coverage: { covered: 300, missed: 200, total: 500, percentage: 60.0 },
          threshold: 75,
          passed: false,
        },
      ],
    };

    const report = generateMarkdownReport(coverage, 'Coverage Report');

    expect(report).toContain('**Overall Coverage: 73.3%**');
    expect(report).toContain(':core:common');
    expect(report).toContain('80.0%');
    expect(report).toContain('✅');
    expect(report).toContain(':core:testing');
    expect(report).toContain('N/A');
    expect(report).toContain('⚠️');
    expect(report).toContain(':data:repository');
    expect(report).toContain('60.0%');
    expect(report).toContain('❌');
  });

  it('should format coverage percentages to 1 decimal place', () => {
    const coverage: OverallCoverage = {
      percentage: 85.567,
      covered: 855,
      total: 1000,
      modules: [
        {
          module: ':app',
          coverage: { covered: 855, missed: 145, total: 1000, percentage: 85.567 },
          threshold: 80,
          passed: true,
        },
      ],
    };

    const report = generateMarkdownReport(coverage, 'Coverage Report');

    expect(report).toContain('**Overall Coverage: 85.6%**');
    expect(report).toContain('| :app | 85.6% |');
  });

  it('should use custom title', () => {
    const coverage: OverallCoverage = {
      percentage: 85.5,
      covered: 855,
      total: 1000,
      modules: [],
    };

    const report = generateMarkdownReport(coverage, 'My Custom Report Title');

    expect(report).toContain('## 📊 My Custom Report Title');
  });

  it('should handle empty modules list', () => {
    const coverage: OverallCoverage = {
      percentage: 0,
      covered: 0,
      total: 0,
      modules: [],
    };

    const report = generateMarkdownReport(coverage, 'Coverage Report');

    expect(report).toContain('## 📊 Coverage Report');
    expect(report).toContain('**Overall Coverage: 0.0%**');
    expect(report).toContain('### Module Coverage');
  });
});
